CC      = gcc34
#PROF    = -p
NOCRYPT =

# Uncomment the two lines below if compiling on a Solaris box
#SOLARIS_FLAG = -Dsun -DSYSV
#SOLARIS_LINK = -lnsl -lsocket

#Uncomment the line below if you are getting a line like:
#interp.c:757: warning: int format, time_t arg (arg 7)
TIME = -DTIMEFORMAT

#Uncomment the line below if you are getting implicit decleration of re_exec
#REG = -DREGEX

#Uncomment the line below if you are getting undefined re_exec errors
NEED_REG = -lgnuregex

#Uncomment the line below if you are getting undefined crypt errors
NEED_CRYPT = -lcrypt

#Comment it out if you get errors about ldl not being found.
NEED_DL = -ldl

#DBUGFLG = -DREQUESTS

#Uncomment the line below if you want a performance increase though beware
#your core files may not be as much of a benefit if you do.
#OPT_FLAG = -finline-functions -funroll-loops -fdefer-pop -fstrength-reduce

C_FLAGS = $(OPT_FLAG) -O -g3 -w -Wall -Wuninitialized $(PROF) $(NOCRYPT) $(DBUGFLG) -DSMAUG $(SOLARIS_FLAG) $(TIME) $(REG)
L_FLAGS = $(OPT_FLAG) $(PROF) $(SOLARIS_LINK) $(NEED_DL) $(NEED_CRYPT) ~/HouseOfGhouls/src/liblua.a -lm 

C_FILES = act_comm.c act_info.c act_move.c act_obj.c act_wiz.c boards.c \
          build.c clans.c comm.c comments.c const.c db.c deity.c fight.c \
          handler.c hashstr.c ident.c interp.c magic.c makeobjs.c \
          mapout.c misc.c mpxset.c mud_comm.c mud_prog.c player.c polymorph.c \
          requests.c reset.c save.c shops.c skills.c special.c tables.c \
          track.c update.c grub.c stat_obj.c ban.c services.c \
          imm_host.c color.c quest.c healer.c bank.c hotboot.c \
          alias.c marry.c bottle.c locker.c pfiles.c editor.c \
          ratings.c undertaker.c slay.c train.c liquids.c antitank.c \
          acro.c gambler.c \
          lua_scripting.c lua_bits.c mt19937ar.c lua_tables.c

O_FILES = act_comm.o act_info.o act_move.o act_obj.o act_wiz.o boards.o \
          build.o clans.o comm.o comments.o const.o db.o deity.o fight.o \
          handler.o hashstr.o ident.o interp.o magic.o makeobjs.o \
          mapout.o misc.o mpxset.o mud_comm.o mud_prog.o player.o polymorph.o \
          requests.o reset.o save.o shops.o skills.o special.o tables.o \
          track.o update.o grub.o stat_obj.o ban.o services.o \
          imm_host.o color.o quest.o healer.o bank.o hotboot.o \
	      alias.o marry.o bottle.o locker.o pfiles.o editor.o \
          ratings.o undertaker.o slay.o train.o liquids.o antitank.o \
	      acro.o gambler.o \
	      lua_scripting.o lua_bits.o mt19937ar.o lua_tables.o

H_FILES = mud.h bet.h bank.h hotboot.h alias.h pfiles.h slay.h liquids.h

all:	
	make smaug

smaug: $(O_FILES)

	$(CC) $(L_FLAGS) $(USE_IMC) -o smaug $(O_FILES) ~/HouseOfGhouls/src/liblua.a
	chmod g+w smaug
	chmod a+x smaug
	chmod g+w $(O_FILES)

.c.o: mud.h
	$(CC) -c $(C_FLAGS) $(USE_IMC) $<

clean:
	rm -f *.o smaug *~
